### ISSUE TITLE
Can't build multiple query

### ISSUE THREAD

**Issue by gusdecool** [Floby/node-url-assembler#7]
we can't build add multiple query :(

example this init code

```js
const foo = UrlAssembler()
  .template('/users/:user')
  .param('user', 8)
  .param('include', 'address')
  .query({
    some: 'thing',
    other: 1234
  })
  .toString() // => "/users/8?include=address&some=thing&other=1234

foo.query('alpha', 'beta'); // this additional query will not added :(
```

I were expecting we can continuously add more URL query 😭

**Comment by Floby** [comment]
Hello, I can replicate _a_ bug with this test, but it doesn't seem to do the same as yours. can your confirm ?

```javascript
describe('when called after a multi query call', () => {
  beforeEach(() => myUrl.query({a: 8, b: true}))
  it('adds the new query parameter', () => {
    expect(myUrl.query('c', 'hello').toString()).to.equal('/hello?a=8&b=true&c=hello')
  })
})
```
I get

```
  1) an instance with no baseUrl given a template with no parameters .query(key, value) when called after a multi query call adds the new query parameter:

      AssertionError: expected '/hello?c=hello' to equal '/hello?a=8&b=true&c=hello'
      + expected - actual

      -/hello?c=hello
      +/hello?a=8&b=true&c=hello
      

```

**Comment by alexfoxgill** [comment]
`.query()` doesn't mutate the object, it returns a new one:

https://runkit.com/5b2bbe0e6bb7720012426f93/5b2bbe156bb7720012426f98

**Comment by gusdecool** [comment]
@alexfoxgill thank you, exactly what i mean.

**Comment by Floby** [comment]
I think what you are describing is intended. no mutation in previously defined urls. All method return a brand new instance. As a matter of fact, if you find a case where a mutation occurs, please report it as a bug ;)
